[project]
name = "vaultx"
description = "A decentralized vault for secure STX storage"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.vault]
path = "contracts/vault.clar"
clarity_version = 2
epoch = 2.5
